name: AppleScript Syntax Check
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  compile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate AppleScript
        run: osascript -l AppleScript login.scpt
